// mobile/src/screens/room/components/message-composer/index.tsx
import { useRef } from "react";
import { Pressable, View } from "react-native";
import { InfiniteData, useQueryClient } from "@tanstack/react-query";

import { Input } from "@/components/input";
import { Send } from "@/components/icons/send";
import { COLORS } from "@/styles";
import { socket } from "../../libs/socket-io";
import { InfiniteMessageListResponse } from "../../hooks/use-infinite-message-list";
import { styles } from "./styles";

interface Props {
  id: string;
}

export function MessageComposer({ id }: Props) {
  const message = useRef("");
  const queryClient = useQueryClient();

  const handleSendMessage = async () => {
    queryClient.invalidateQueries(["rooms"]);
    await queryClient.cancelQueries(["rooms", id, "messages"]);

    queryClient.setQueryData<InfiniteData<InfiniteMessageListResponse>>(
      ["rooms", id, "messages"],
      (prev) => ({
        ...prev!,
        pages: [
          {
            messages: [
              {
                id: new Date().getTime().toString(10),
                content: message.current,
                roomId: id,
                isFromAi: false,
                createdAt: new Date(),
              },
            ],
            metadata: {
              nextCursor: -1,
            },
          },
          ...prev?.pages!,
        ],
      })
    );

    socket.emit("message.new", { content: message.current, roomId: id });
  };

  return (
    <View style={styles.wrapper}>
      <View style={styles.inputWrapper}>
        <Input
          multiline
          placeholder="Message"
          style={styles.input}
          onChangeText={(text) => (message.current = text)}
        />
      </View>
      <Pressable style={styles.send} onPressIn={handleSendMessage}>
        <View style={styles.sendIconWrapper}>
          <Send stroke={COLORS.blue.ios} />
        </View>
      </Pressable>
    </View>
  );
}

// web/src/routes/room/[id]/components/message-composer.svelte
<script lang="ts">
	import { useQueryClient } from '@tanstack/svelte-query';
	import { page } from '$app/stores';
	import Input from '$lib/components/input.svelte';
	import Send from '$lib/components/icons/send.svelte';
	import { socket } from '../libs/socket-io';

	let message = '';
	let queryClient = useQueryClient();
	$: id = $page.params.id;

	function handleSendMessage() {
		socket.emit('message.new', { content: message, roomId: id });

		queryClient.invalidateQueries({
			queryKey: ['rooms', id, 'messages']
		});

		message = '';
	}
</script>

<div class="w-full py-6">
	<form
		class="w-full max-w-3xl mx-auto flex items-end gap-4"
		on:submit|preventDefault={handleSendMessage}
	>
		<Input
			name="message"
			id="message"
			classNames="max-h-52 p-3 bg-neutral-700 rounded-2xl"
			placeholder="Message"
			bind:value={message}
		/>
		<button class="p-3">
			<div class="h-6 aspect-square">
				<Send class="stroke-blue-500" />
			</div>
		</button>
	</form>
</div>
